#!/usr/bin/env bash

templates_path="$HOME/.i3/i3-resurrect/templates"

template_name=$(ls -t "$templates_path" | dmenu -p Template -fn 'Hack Nerd Font-11'  -i | xargs)

if [[ "$template_name" == "" ]]; then
  echo "Invalid template"
  exit 1
fi

template_path="$templates_path/$template_name"
/usr/bin/xterm -e "cd $template_path && vim layout.json programs.json"
