name: On dispatch

on:
  repository_dispatch:
    types: [build]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Bump
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: git-checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Patch
        run: |
          npm install -g npm@7.24.0
          git config --global user.name 'thoughtsunificator'
          git config --global user.email 'oss@thoughtsunificator.me'
          npm version patch
          git push
          git push --tags
